name: Trigger auto deployment for appdecontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/appdecontainer-AutoDeployTrigger-6b7932ab-692c-47c0-87aa-73861ce2e58c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: oficialcontainerrg.azurecr.io
          username: ${{ secrets.APPDECONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.APPDECONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: oficialcontainerrg.azurecr.io/oficial:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APPDECONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n appdecontainer -g aplicativo --server oficialcontainerrg.azurecr.io --username  ${{ secrets.APPDECONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.APPDECONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n appdecontainer -g aplicativo --image oficialcontainerrg.azurecr.io/oficial:${{ github.sha }}
